### ISSUE TITLE
Cannot query field "allStripeSku" on type "Query" even with a valid secret key

### ISSUE THREAD

**Issue by develo-pera** [thorsten-stripe/ecommerce-gatsby-tutorial#13]
I read in [one closed issue](https://github.com/thorsten-stripe/ecommerce-gatsby-tutorial/issues/2) that this can happen because of the wrong Stripe secret key, but I don't think that's the reason in my case. I've added the right secret key exactly as described here: [https://www.gatsbyjs.org/tutorial/ecommerce-tutorial/](https://www.gatsbyjs.org/tutorial/ecommerce-tutorial/), I've even hardcoded it and it still doesn't work, I rolled the secret key and tried with the new one and I have the same problem. I even created a new account and still the same

Gatsby CLI version: 2.8.11
Gatsby version: 2.17.11
Node version: 10.16.0

**Comment by ramanagh** [comment]
I also had same issue. Fixed with following change. In checkout.js as in the tutorial, update the following line with your product SKU from your stripe test products and it will work.
async redirectToCheckout(event) {
    event.preventDefault()
    const { error } = await this.stripe.redirectToCheckout({
      items: [{ sku: **"sku_GFvkCaY0FvZyzz"**, quantity: 1 }],
      successUrl: `http://localhost:8000/page-2/`,
      cancelUrl: `http://localhost:8000/`,
    })

**Comment by thorsten-stripe** [comment]
Sorry for the crazy delay here, I wasn't monitoring the repo 🙈 

I just pushed an update that moves all stripe ids and keys to the `.env` file. Can you retry? 

Do make sure you have the .env file setup `cp .env.example .env.development` and your keys added
