### ISSUE TITLE
Inventory numbers with client-only stripe checkout

### ISSUE THREAD

**Issue by codeconomy** [thorsten-stripe/ecommerce-gatsby-tutorial#21]
Great share! Thanks for this!

Unsure if this is the best place to post feedback but here it comes :)

As I explore implementing client-only stripe checkout on a Gatsby e-commerce site, I realise a great improvement would be to be able to do be able to surface numbers of items left from an "inventory list" in Stripe.

A lot of people using client-only stripe checkout sell a small number of items (many times only a limited number - handmade items, one-off, etc), so being able to limit the sales to what is available in the inventory would be great. Simple this is such a simple "inventory" I wouldn't want to integrate any inventory management third-party...

Additionally, it would be great if one could read that #number of items through an API (as I'd like to print that to the item presentation saying "only 6 items left" for instance).

Thanks again for this!

**Comment by thorsten-stripe** [comment]
Thanks for the feedback @codeconomy, I have forwarded it to the Checkout team internally.

For the time being you would need to use come commerce API for this, or you would have to track inventory on your end via e Netlify function for example.

Thanks again for the feedback, if you have additionally feedback please email: checkout-feedback@stripe.com

To stay up to date with changes to Checkout, you can subscribe here: https://stripe.com/docs/payments/checkout#checkout-roadmap

**Comment by codeconomy** [comment]
Thanks for the input. Will explore the idea to use Netlify functions. Good one.
All Best

**Comment by thorsten-stripe** [comment]
In case helpful, Jason and I did a stream on using Netlify functions with Stripe: https://www.learnwithjason.dev/sell-products-on-the-jamstack

**Comment by codeconomy** [comment]
That is Brilliant!!!

Thanks for the share!
