### ISSUE TITLE
Checkout button issue

### ISSUE THREAD

**Issue by good3n** [thorsten-stripe/ecommerce-gatsby-tutorial#23]
Hello!

I've been following your tutorial on Gatsby e-commerce, and noticed an issue with the "Checkout" button on your [advanced cart tree](https://github.com/thorsten-stripe/ecommerce-gatsby-tutorial/tree/cart-example).

I fired it up, and with nothing added to the cart, the button was enabled still by default.

On the [advancedCheckout.js](https://github.com/thorsten-stripe/ecommerce-gatsby-tutorial/blob/cart-example/src/components/advancedCheckout.js) component you use `props.cart.length` frequently for different functionality (like disabling the checkout button). However, because the cart is initially an empty array ([here](https://github.com/thorsten-stripe/ecommerce-gatsby-tutorial/blob/cart-example/src/components/Cart.js) on line 7), when I `console.log(props.cart)` I get both the empty array and then the updated array. (screenshot attached)

Due to the cart returning an empty array first before the component mounts, it's producing inconsistent results when checking the `length` of `props.cart`

<img width="329" alt="Screen Shot 2020-04-27 at 2 16 38 PM" src="https://user-images.githubusercontent.com/7230649/80406290-d4cc0f80-8891-11ea-89a8-1df4e2e1dbf2.png">

**Comment by thorsten-stripe** [comment]
Hi @good3n yah, the integration wasn't great. I'm actually working on a refactor and using a react cart library: https://github.com/thorsten-stripe/ecommerce-gatsby-tutorial/pull/24
