### ISSUE TITLE
Netlify test deployment fails

### ISSUE THREAD

**Issue by DOSputin** [thorsten-stripe/ecommerce-gatsby-tutorial#5]
Trying the vanilla 
![image](https://user-images.githubusercontent.com/32726022/62002966-72a46b00-b0c3-11e9-95ff-1060376054d4.png)

![image](https://user-images.githubusercontent.com/32726022/62002956-425ccc80-b0c3-11e9-947b-12b321f8a948.png)

```sh
$: error #85907 GRAPHQL  There was an error in your GraphQL query:
$: - Unknown field 'attributes' on type 'StripeSku!'.
$: File: src/components/Products/Skus.js
```

Seems that this is unrelated to #3 and #4  

Using the correct `sk_test_key`

**Comment by thorsten-stripe** [comment]
Unfortunately there are some IDs hardcoded in the query: https://github.com/thorsten-stripe/ecommerce-gatsby-tutorial/blob/master/src/components/Products/Skus.js#L35 that you will have to replace with the relevant product ID from your Stripe account. 

I'll hope to change this example to get rid of the hardcoded product ID soon.

**Comment by thorsten-stripe** [comment]
I've fixed this and added a setup section to the README[0]. I've tested with a fresh Stripe account, so hopefully this should now work for you. Please reopen if you're still facing issues.

[0] https://github.com/thorsten-stripe/ecommerce-gatsby-tutorial#setup
